# https://github.com/sclorg/postgresql-container/tree/generated/10
version: '3.7'

services:
  db:
    image: centos/postgresql-10-centos7
    # restart: always
    environment:
      POSTGRESQL_DATABASE: fswd1
      POSTGRESQL_USER: fswd
      POSTGRESQL_PASSWORD: example
      POSTGRESQL_ADMIN_PASSWORD: example
    volumes:
      - ./db-data:/var/lib/pgsql/data #sudo setfacl -m u:26:-wx ./db-data
    expose:
      - 5432
    networks:
      default:
        aliases:
          - db

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
    networks:
      default:

  backend:
    container_name: backend
    build:
      context: .
     image: ${CI_DOCKER_REGISTRY}/fullstackcicd-runner/fswd-apollo-typeorm-pg:${CI_COMMIT_REF_SLUG:-latest}
    volumes:
      - './:/usr/src/app/'
      - '/usr/src/app/node_modules'
    depends_on:
      - start_dependencies
    expose:
      - 3000
    ports:
      # - '3000:3000'
      - 9229:9229
      - 9230:9230
    environment:
      - NODE_ENV=staging
    networks:
      outside:
      default:
        aliases:
          - backend

networks:
  outside:
    internal: false
  default:
    name: fswd
    internal: true
   
